[package]
name = "rssflow-service"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
rssflow-proto.workspace = true

prost.workspace = true
prost-types.workspace = true

axum.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection = "0.13"

tokio.workspace = true
futures.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

anyhow.workspace = true
confique = { version = "0.3", default-features = false, features = ["toml"] }

url = { workspace = true, features = ["serde"] }