services:
  rssflow:
    image: localhost/rssflow:latest
    ports:
      - 3434:3434
  websub:
    image: localhost/rssflow-websub:latest
    ports:
      - 3435:3435
  fetch:
    image: localhost/rssflow-fetch:latest
  filter:
    image: localhost/rssflow-filter:latest
  replace:
    image: localhost/rssflow-replace:latest
  retrieve:
    image: localhost/rssflow-retrieve:latest
  sanitize:
    image: localhost/rssflow-sanitize:latest

  #  docker run -d -p4317:4317 -p16686:16686 jaegertracing/all-in-one:latest

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4317:4317
      - 16686:16686

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: rssflow
      POSTGRES_PASSWORD: rssflow
      POSTGRES_DB: rssflow-websub
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    image: valkey/valkey:latest
    ports:
      - 6379:6379

volumes:
  postgres-data: